---
name: Python Package

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libgl1 libglib2.0-0
          python -m pip install --upgrade pip
          pip install -r requirements.txt flake8 coverage

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report -m
          coverage xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
