name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Check directory structure
        run: ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install flake8 coverage || true

      - name: Lint with flake8
        run: |
          flake8 . || true

      - name: Run tests with coverage
        run: |
          coverage run -m pytest || true
          coverage report -m || true